driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3

platforms:
  - name: centos-7.0
    run_list: yum-epel::default
  - name: centos-6.5
    run_list: yum-epel::default
  - name: centos-5.10
    run_list: yum-epel::default
  - name: debian-7.2.0
    run_list: apt::default
  - name: debian-6.0.8
    run_list: apt::default
  - name: freebsd-9.2
    run_list:
      - freebsd::portsnap
      - freebsd::pkgng
  - name: freebsd-10.0
    run_list: freebsd::portsnap
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-13.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-10.04
    run_list: apt::default
  # Talk to the OCIV team if you need access to the Solaris development infra.
<%
{
  'solaris-11-i86pc' => {
    global_zone_hostname: 'virtsol01.chef.co',
    master_zone_ip:       '172.31.9.84',
    test_zone_ip:         '172.31.9.86',
  },
  'solaris-10-i86pc' => {
    global_zone_hostname: 'virtsol02.chef.co',
    master_zone_ip:       '172.31.9.36',
    test_zone_ip:         '172.31.9.38',
  },
  'solaris-11-sun4v' => {
    global_zone_hostname: 'virtsol03.chef.co',
    master_zone_ip:       '172.31.9.60',
    test_zone_ip:         '172.31.9.62',
  },
  'solaris-10-sun4v' => {
    global_zone_hostname: 'virtsol04.chef.co',
    master_zone_ip:       '172.31.9.12',
    test_zone_ip:         '172.31.9.14',
  },
}.each_pair do |platform_name, options| %>
  - name: <%= platform_name %>
    provisioner:
      sudo_command: <%= platform_name =~ /solaris-10/ ? '/usr/local/bin/sudo -E' : 'sudo -E' %>
    verifier:
      sudo_command: <%= platform_name =~ /solaris-10/ ? '/usr/local/bin/sudo -E' : 'sudo -E' %>
    driver:
      name: zone
      global_zone_hostname: <%= options[:global_zone_hostname] %>
      global_zone_password: <%= ENV['KITCHEN_ZONE_GLOBAL_ZONE_PASSWORD'] %>
      master_zone_name: kitchen-master
      master_zone_ip: <%= options[:master_zone_ip] %>
      # TODO: Assign ipaddresses automatically
      test_zone_ip: <%= options[:test_zone_ip] %>
<% end %>
  #
  # The following (private) boxes are shared via Atlas. Please note this
  # requires adding your Atlans account to the `Chef` org and will
  # require a `vagrant login`.
  #
  # The Mac OS X boxes are VMware only also. You can enable VMware Fusion
  # as the default provider by copying `.kitchen.local.yml.vmware.example`
  # over to `.kitchen.local.yml`.
  #
  - name: macosx-10.8
    driver:
      box: chef/macosx-10.8 # private
  - name: macosx-10.9
    driver:
      box: chef/macosx-10.9 # private
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private
  - name: windows-7-professional
    driver:
      box: chef/windows-7-professional # private
  - name: windows-8.1-professional
    driver:
      box: chef/windows-8.1-professional # private
  - name: windows-2008r2-standard
    driver:
      box: chef/windows-server-2008r2-standard # private

suites:
  - name: default
    run_list: omnibus::default
