---
driver:
  name: ec2

  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] || ENV['USER'] %>

  flavor_id: <%= ENV['INSTANCE_FLAVOR'] %>

  region: <%= ENV['AWS_REGION'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  security_group_ids: <%= ENV['AWS_SECURITY_GROUP_IDS'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  interface: <%= ENV['AWS_INTERFACE'] %>

  require_chef_omnibus: true
platforms:
  - name: rhel-7.0
    driver:
      image_id: ami-785bae10
      username: ec2-user
